# Persistent Volume Claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: simple-iozone-pvc-ceph
  annotations:
    #volume.alpha.kubernetes.io/storage-class: standard
    v1.storage.k8s.io/storage-class: ceph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
