apiVersion: batch/v1
kind: Job
metadata:
  name: simple-iozone-job
spec:
  completions: 1
  template:
    metadata:	  
      name: simple-iozone-job
    spec:
      volumes:
      - name: simple-iozone-data-volume
        persistentVolumeClaim: 
          claimName: simple-iozone-pvc-ceph

      containers:
      - name: iozone
        image: agtestorg/simple-iozone:0.0.1
#        command: [ "/bin/bash", "-c", "/home/iozone/keep-alive.sh" ]  # uncomment if you would like to run the container and exec in
        imagePullPolicy: Always

        volumeMounts:
        - name: simple-iozone-data-volume
          mountPath: "/data"
      restartPolicy: Never
